### ISSUE TITLE
Adding optional $lang param

### ISSUE THREAD

**Issue by BaseMax** [BaseMax/GooglePlayWebServiceAPI#8]
Hey,

If anyone is interested in doing this, we welcome it.

```php
$app=$google->parseApplication("com.bezapps.flowdiademo", "en..");
$app=$google->parseApplication("com.bezapps.flowdiademo", "de..");
$app=$google->parseApplication("com.bezapps.flowdiademo", "fa..");
...
```

Thanks

**Comment by BaseMax** [comment]
cc @IzzySoft

**Comment by IzzySoft** [comment]
Added to my list. That one should be rather easy. You want it for permissions, too?

Restriction: It might only be ISO-631 (eg `en`, not `en-US`), need to dig in. Second half would be the `gl` (geoLocation) parameter, might fit to `parseApplication()`.

**Comment by IzzySoft** [comment]
PS: I cannot self-assign as I'm no member. Your decision if you'd want that. I'm open to it – but am not sure you mind the consequences (or already trust me enough). Usual GPL-disclaimer: "…AS-IS…NO WARRANTY…" – but of course I wouldn't intentionally "screw up things" :laughing:

OTOH: As you put it, this would be a "good first issue" as it should be pretty easy :wink:

**Comment by BaseMax** [comment]
> You want it for permissions, too?

Yes, because they are also automatically translated.

Thanks,

**Comment by BaseMax** [comment]
>  IzzySoft has been added as a collaborator on the repository. 

I invited you.
But if possible, please continue in PR. Because it is separated and there is an explanation and history for each case.

Thank you.
